server:
  port: 8009

spring:
  devtools:
    livereload:
      enabled: true
#  profiles:
#    active : DEV

  data:
    mongodb:
      uri: mongodb://localhost:27018/retailitemservice
      repositories:
        type: AUTO