#server:
#  port: 9200
spring:
  application:
    name: ws-retail-itemservice
  devtools:
    livereload:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/reach-engine
      username: root
      password: rootpassword
      repositories:
        type: AUTO

logging:
  level:
    org:
      mongodb=DEBUG: